### ISSUE TITLE
Mod with an available update do not change color until you click inside the mod list.

### ISSUE THREAD

**Issue by 4o66** [MacTee/KSP-Mod-Admin-aOS#103]
After running the Check all mods for updates process via the button, none of the mods drop from green to blue unless I click inside the mod list.

I am not sure how to trigger a refresh of the mod tree after the check for updates process completes.

**Comment by MacTee** [comment]
Fixed with commit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/ee12c79f624b0f08fb7bd4749ef4a4140b771207
