### ISSUE TITLE
Key MSG_SCAN_ERROR_DURING_SCAN is not defined for language eng!

### ISSUE THREAD

**Issue by sarbian** [MacTee/KSP-Mod-Admin-aOS#111]
I guess the title says it all :)

When scanning I had an error (related to me using a windows junction that pointed to a deleted dir, so all my fault) and I had this in a log :+1: 
Key MSG_SCAN_ERROR_DURING_SCAN is not defined for language eng!

**Comment by MacTee** [comment]
Fixed with comit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/28a8d73d0d14e7e1a9428db741308ee8df1acae5.
