### ISSUE TITLE
Error when downloading from URL

### ISSUE THREAD

**Issue by JacobGrayUSA** [MacTee/KSP-Mod-Admin-aOS#112]
When I try to download a new mod from any source via URL, I get this error message:

![capture](https://cloud.githubusercontent.com/assets/8125286/7789729/78125256-0239-11e5-9677-21b6b6cd00f0.PNG)
![capture2](https://cloud.githubusercontent.com/assets/8125286/7789730/7a635302-0239-11e5-9fbd-99a56162a585.PNG)
![capture3](https://cloud.githubusercontent.com/assets/8125286/7789731/7c789c56-0239-11e5-945d-4509d31ebc14.PNG)

On Windows 7

Sorry I'm not much of a programmer, I can't seem to find any other logs.

**Comment by MacTee** [comment]
Thanks for the report,
Try to add links without "\files\latest", that schould help.
I'll fix this with the next version.

**Comment by MacTee** [comment]
hmm, i thought i could reproduce the problem, but i have just made a typo in the url.

After some more testing i'm only able to reproduce this error (the two exceptions) when i have a typo in the url (as you can see in the above coment "\").

When i copy the link of the CurseForge download button (<CurseForgeURL>/<mod>/files/latest) and paste it to the URL TextBox of the Add mod dialog all works fine.
Did you do something special?

**Comment by JacobGrayUSA** [comment]
Ok so tried it again today

![capture4](https://cloud.githubusercontent.com/assets/8125286/7800381/7268593c-02e2-11e5-9bb6-1804b04c1894.PNG)

And now, this comes up

![capture6](https://cloud.githubusercontent.com/assets/8125286/7800396/a3e61350-02e2-11e5-81a8-7937ff052745.PNG)
![capture7](https://cloud.githubusercontent.com/assets/8125286/7800395/a3e50320-02e2-11e5-9f4b-9f0a5550af41.PNG)
![capture5](https://cloud.githubusercontent.com/assets/8125286/7800394/a3e42b3a-02e2-11e5-917e-0565b157d1e2.PNG)

so i tried this instead

![capture8](https://cloud.githubusercontent.com/assets/8125286/7800406/ce029410-02e2-11e5-8058-65c38669f28c.PNG)

and it goes back to the original problem!
:(

**Comment by MacTee** [comment]
hmm ... I'm still not able to reproduce the problem.
Pls try the new version 2.0.0.2 and if you still encounter this problem send me the KSPMA.log from the KMA² install folder.

**Comment by JacobGrayUSA** [comment]
looks like it's all cleared up now! if it happens again, i'll be sure to send you the .log instead of crappy screen shots :P

**Comment by MacTee** [comment]
Good to hear that it works now. =)
