### ISSUE TITLE
"MSG_PLEASE_SELECT_SOLVING_MODS" shows even after all conflicts are solved

### ISSUE THREAD

**Issue by diomedea** [MacTee/KSP-Mod-Admin-aOS#113]
Title seems to say it all.
The specific message (dialog will show "Please select a solving mod for this conflict files:") appears after all conflicts have been manually dealt with from the conflict solver window. 
It would be expected the message to show only in case conflicts still remain.

**Comment by MacTee** [comment]
Fixed with commit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/a6e97280e0af214d261952f25c27df0bcd49cd77
