### ISSUE TITLE
Resolution detection is not working correctly in (my) multi-display setup

### ISSUE THREAD

**Issue by TheVoidSeeker** [MacTee/KSP-Mod-Admin-aOS#117]
The resolution combo-box only shows the (way lower) resolutions of my **secondary display**, instead of those of my **primary**.

I don't know exactly why WMI returns the value for the secondary display, when querying the video controller interface. A *quick* google didn't help in finding a better WMI query.

When i removed the WMI call or returned an empty resolutions list in **GetResolutionsViaWMI**, the **GetResolutionsViaNativeMethods** function returned the correct ones for me.

Maybe add a field to select your display? Or at least remove/fix the WMI query, please.

**KSP Mod Admin Version:** 2.2.0.2
**OS:** Win 8 x64

**Comment by MacTee** [comment]
Hmm let me think how I'll handel this.
Thanks for your report!

**Comment by 4o66** [comment]
Can confirm, only seeing resolutions from the primary display.

**Comment by WCapelle** [comment]
I spent a while when I first noticed the issue looking up solutions, and the only things I could find would not have been cross-platform. Something can probably be done that looks at the platform it's running on, but I didn't want to mess with it, not having a linux system to test on.

The crummy solution I came up with was to set it via the KSP launcher settings, and then never touch resolution on KSPMA.


The more permanent solution I found was to mess with the video driver configuration applet until I was able to force one monitor to be primary over the other. What I found out was that on my video card (an AMD) and probably others is that the order of the ports matters. At the time I had a Display Port to VGA adapter, and then an HDMI to DVI cable. The Display Port is port 1 on my card, then HDMI, then the standard DVI. My secondary monitor was plugged into the VGA adapter, and my primary ran off the HDMI cable. Windows was looking at that ordering for primary and secondary, and didn't care how they were actually set up in the settings. From what I found looking into it, that's just the way Windows is about it, and there's nothing you can change (fiddling with the display driver stuff fixed it I think, but I also have new monitors that are the same resolution now).

**Comment by MacTee** [comment]
This commit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/fe9ed83f9425f162eb020c98c116bf54fc4ed9b5 should fix the issue

**Comment by MacTee** [comment]
Any news about this bug is it fixed?
