### ISSUE TITLE
KSPModAdmin.core.dll already exists

### ISSUE THREAD

**Issue by atabbott** [MacTee/KSP-Mod-Admin-aOS#125]
When I try and run KSP Mod Admin v2.3.0.1 on OSX 10.10.3 I get the error message attached below. I have also included the KSPMA.log as well although it looks as if it included very little information in this case. 
![screen shot 2015-06-07 at 14 41 23](https://cloud.githubusercontent.com/assets/10086881/8024238/7d7d13fc-0d24-11e5-8e24-632646b53208.png)

KSPMA.log:
[07.06.2015 14:38:32.161] [1] Info    : ---> KSP MA v2.3.0.1 started <---
[07.06.2015 14:38:32.169] [1] Debug   : Loading languages ...
[07.06.2015 14:38:32.251] [1] Debug   : Loading languages done. (English, Deutsch, Italiano, Русский)
[07.06.2015 14:38:32.978] [1] Debug   : Creating config directory: /Users/Aidan/Library/Application Support/Steam/steamapps/common/Kerbal Space Program/Zmods/KSPModAdmin-v2.3.0.1_Mono/v2.3.0.1/KSP Mod Admin/KSPModAdmin.Core.dll

I've tried removing and renaming the KSPModAdmin.core.dll this causes another error to be thrown in terminal however.

I was experiencing the same issue as draktheas (from the general release forums) on v2.3.0.0. So moving bsck to that version is not feasible.

If I'm doing something wrong could you let me know, but I have just unzipped the file and am attempting to execute it via mono as stated in the release instructions.

**Comment by MacTee** [comment]
Hi atabbott,
thanks for the report.
I have a fix for the issue with commit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/fcc655c73d68454078764a40e7b012509771b8cc.
You can download a fixed version here:
http://www.services.mactee.de/KSP/download/KSPModAdmin-v2.3.0.2_Mono_MacFixes.zip

**Comment by MacTee** [comment]
Any news about the quick fix from above?
I don't have a Mac to test on =(

**Comment by atabbott** [comment]
Yes! The fix worked very well, application opens without any problem and
works great for installing and managing mods!

I don't know if this is Mac specific or not, or even just a quirk of my
system but whenever I open the application I need to navigate to my KSP
install folder every time.

I'm also really looking forward to the mod navigators for Kerbal stuff and
Curse I believe you are building, as mono on the Mac doesn't allow you to
copy from the general OS and paste into it. It has its own completely
separate clipboard. Have to manually type out each URL.

Thanks for all the work so far! It's great!

**Comment by MacTee** [comment]
Wow no copy & past ... [after some research] ... this is a long known bug in mono, which got never fixed.
For now i have no fix or workaround =(

Normaly KMA² should save the last selected KSP folder and selects is on startup.
Could you send me the KSPModAdmin_aOS.cfg and the KSPMA.log from your KMA² install forlder.
mackerbal@mactee.de
