### ISSUE TITLE
Checking for mod updates at startup runs before showForm

### ISSUE THREAD

**Issue by 4o66** [MacTee/KSP-Mod-Admin-aOS#127]
On a heavily modded install of KSP using "Update check interval: On startup" can keep the main form from showing for a (relatively) long amount of time. (In my case 20+ seconds.)

While this seems like a trivial amount of time, it makes it seem like the application has not actually launched. Would it be possible to move the check for updates action to after the main form has become visible?

**Comment by MacTee** [comment]
A solution to this could be:
Let the MainController listen to the KSPMAStarted event and move the two update functions (OptionsController.Check4AppUpdates() & OptionsController.Check4ModUpdates(true)) to the event handling method.

**Comment by MacTee** [comment]
Fixed with commit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/8c37d0c7586815ee285f8229e59947f2205541aa.
