### ISSUE TITLE
KerbalStuff URLs Not Recognized as Valid

### ISSUE THREAD

**Issue by theslams** [MacTee/KSP-Mod-Admin-aOS#132]
Using 2.3.0.2, attempting to add new KerbalStuff sourced mods is resulting in "Attention! Please enter a valid archive path or URL.:

Attempting to add ModInfo to a mod added via ZIP archive by entering the URL and scanning for ModInfo results in "Error! No SiteHandler for URL <URL Here> found! Mod Info Update aborded!

Also "aborded" should be "aborted". :)
I ran into this issue attempting to add this mod: http://www.kerbalstuff.com/mod/927/Docking%20Sounds
But couldn't get any randomly entered mods to add successfully.

**Comment by MacTee** [comment]
Hi theslams,

thanks for the report!
A workaround for this issue is to remove the "www." from the URL.
I'll release a fix as fast as possible!

**Comment by MacTee** [comment]
fixed with commit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/d32ee0c3c78d6f385878cffb8b92b1c691c90b5d

**Comment by alex-samodurov** [comment]
Thanks for the quick fix.

Just as a side note: this tool is great and I use it exclusively for mod management (66 mods, so far). Your work is appreciated!
