### ISSUE TITLE
Some Kerbal Stuff urls not working or contain invalid characters.

### ISSUE THREAD

**Issue by thakyZ** [MacTee/KSP-Mod-Admin-aOS#139]
Hi so I went back to windows after posting the last bug report I posted and I have tried to add two mods from Kerbal Stuff and they either do noting or just say "The url contains invalid characters." The two mods urls are: 
[https://kerbalstuff.com/mod/74/In%20game%20notes%20/%20notepad%20/%20checklist](https://kerbalstuff.com/mod/74/In%20game%20notes%20/%20notepad%20/%20checklist)
[https://kerbalstuff.com/mod/1053/Champagne%20Bottle%20%22Lafitte%22](https://kerbalstuff.com/mod/1053/Champagne%20Bottle%20%22Lafitte%22)

**Comment by MacTee** [comment]
A workaround for now could be to remove everything after the number of the mod.
Like: https://kerbalstuff.com/mod/74

**Comment by MacTee** [comment]
Kerbal stuff went down ...
