### ISSUE TITLE
Object Reference not set to Instance of an Object [Windows 10]

### ISSUE THREAD

**Issue by PiggyWhiskey** [MacTee/KSP-Mod-Admin-aOS#140]
Recently got back into KSP and went hunting for a mod manager. CKAN didn't want to update the mods, so I moved to KSPMA.

I started adding the basic mods. (Alarm Clock, Science Alert, Mechjeb etc) and get that error "Object Reference not set to Instance of an Object".

Tested with a few other mods with the same issue.

KSPMA is in my Steam/KSP folder.

Even after running as Admin, same issue.

**Comment by PiggyWhiskey** [comment]
Narrowed it down to line 308 in KSPModAdmin.Core
mResultCall(default(T_RETURN_VALUE), mException);
T_RETURN_VALUE is a 'type parameter', which is not valid in the given context

**Comment by MacTee** [comment]
Thanks for the report!
