### ISSUE TITLE
KMA Adds version to mod folder name, sometimes

### ISSUE THREAD

**Issue by Flatfoot** [MacTee/KSP-Mod-Admin-aOS#152]
I stumbled across a quirk with KSP Mod Admin.  When you URL install or AVC Check files with Github.. it will add the version name to the mod folder in your GameData folder.   This is all fine and dandy, until you have a mod installed (MechJeb2) that has a hardcoded filepath as part of it's initialization routine.

 

Suggestion: Modify KSP Mod Admin to not add the version number to the folder name, when utilizing Github.

**Comment by MacTee** [comment]
@Flatfoot 
The MechJeb2 archive from GitHub is not the compiled mod you need. Its code only.
If you want to use and version control MechJeb, you have to use the CurseForge as a reference.
https://kerbal.curseforge.com/projects/mechjeb

It might be a problem for other mods too.
