### ISSUE TITLE
Borderless option not saved

### ISSUE THREAD

**Issue by AgentRev** [MacTee/KSP-Mod-Admin-aOS#153]
If you check the "Borderless" option below the launch button, and restart Mod Admin, the preference is not remembered. All the other options are restored fine.

Win 10 x64

**Comment by MacTee** [comment]
Fix added with commit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/5574bcae33e51e0aa2fe7eac309f8842ebbc6446. 
Fix will be added to 2.3.0.7 or higher.
