### ISSUE TITLE
False Permissions Error on Linux

### ISSUE THREAD

**Issue by snkiz** [MacTee/KSP-Mod-Admin-aOS#156]
when I close KMA it give me an error about permission to write to the ksp folder, and helpful instructions on how to compromise windows to make it work. (this is not an appropriate program to be run as admin under any circumstances.) 
Except I'm not on windows, and the files its complaining about are in my ksp directory with write permissions.
I'm Hoping this is why I have to tell KMA what language I speak (my computer already knows this.) and where my KSP install is every time it starts. KMA then finds and loads its configs just fine.

**Comment by MacTee** [comment]
KMA needs write permission to:
- its own install folder (in case you use the auto update of KMA)
- the ksp install folder (to write a ksp install specific settings file and install/deinstall of mods)
- a folder where it stores the global settings. 
  Under windows its C:\ProgramData\KSPModAdmin\KSPModAdmin\KSPModAdmin_aOS.cfg
  For Linux it should be $HOME.ksp_mod_admin/KSPModAdmin_aOS.cfg

If KMA can't write it's global settings, you will encounter the discribed problems (language selection, KSP install folders, etc.)

**Comment by MacTee** [comment]
Sry that i haven't seen the relation to issue #151 earlier.
This issue is fixed in 2.3.0.7
