### ISSUE TITLE
System.ArgumentOutOfRangeException: Index was out of range

### ISSUE THREAD

**Issue by official229** [MacTee/KSP-Mod-Admin-aOS#160]
Error and log file provided in pinned zip.

Error showed up after my disk where KSP and KSPModAdmin were installed at got full (0 bytes free).
after clearing up a few Gbs of space the error persisted. I deleted and reinstalled KSPModAdmin but the error persisted. I also tried removing the config files found in KSP root folder but that didn't help.

[logs.zip](https://github.com/MacTee/KSP-Mod-Admin-aOS/files/1284860/logs.zip)

**Comment by MacTee** [comment]
Thanks for the report! I'll dive into it during the next weekend.

**Comment by official229** [comment]
Indeed it works.
Error no longer shows up.
