### ISSUE TITLE
Mod Admin wont even start

### ISSUE THREAD

**Issue by leeky423** [MacTee/KSP-Mod-Admin-aOS#161]
When I downloaded it for some reason there is no way to launch mod admin.  Did I do something wrong or is there a problem?
Thanks!

**Comment by MacTee** [comment]
Hi, where did you download from?

Try one of the download links you find [here](https://github.com/MacTee/KSP-Mod-Admin-aOS/releases/tag/2.3.0.7) (depanding on your system).
