### ISSUE TITLE
Linux: No version control

### ISSUE THREAD

**Issue by hubertnnn** [MacTee/KSP-Mod-Admin-aOS#23]
Version control is always None. Check for updates doesnt work, Tested on Both up to date and outdated mods. In game AVC shows that there is an update for the second one.

**Comment by fr33soul** [comment]
same for me.. all old mods have no version control after lunching first time this manager..

**Comment by MacTee** [comment]
@fr33soul : this is a bug that was fixed 2 years ago. =)
Could you discribe your problem in more detail pls.
(as mentioned above: Version control is only available, if you have added a mod via url or you have edited the ModInfos of a mod (add url and version control manually).)
