### ISSUE TITLE
Difference between dev and master branch

### ISSUE THREAD

**Issue by MacTee** [MacTee/KSP-Mod-Admin-aOS#32]
After i have merged the last dev branch to the master i have noticed that the dev branch is 2 commits behind the master branch.
I think this two commits are the merges from dev to master.
You can see this if you look on the dev branch "https://github.com/MacTee/KSP-Mod-Admin-aOS/tree/dev" in the line below the branch switch button.

Shoud i dump the dev branch after a merge to master and create a new dev branch?
Or is there a way to merge the master against the dev branch (rebase?) again?

**Comment by EoD** [comment]
Usually you have a branch for each feature you are implementing, keeping the branches independent of each other.

Also, you try to never commit directly to your master but always via branches. This way it's guaranteed that the master will build and everyone can see when you have finished (aka "merged") a new feature.

You usually don't re-use one branch like you are doing it in git :)

**Comment by MacTee** [comment]
Thanks for the answer!

I have decided that i won't change my branching which i'm used to.
So there will be a master and a dev branch.
- Master is for releases only (will build always).
- Dev is for further development.
Feature branches will be made from dev and will megred to dev again.
Once a version is stable and ready for release i'll merge dev to master.
To sync master and dev branch again, i'll merge the master with dev branch afterwards.

Tags will come with the first official release.
