### ISSUE TITLE
NullReferenceException on selecting Install Path dropdown 

### ISSUE THREAD

**Issue by EoD** [MacTee/KSP-Mod-Admin-aOS#36]
v2.0.0.10

The program crashes if you select an item in the dropdown menu "KSP Install Path" in the top of the main window. 

Both Windows and Linux backtrace can be found here: https://gist.github.com/EoD/72b9f2271938771f40be

**Comment by MacTee** [comment]
Fixed with commit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/8325e560a22b3e47c4626bd168d7b64afd2ac501
