### ISSUE TITLE
Mod Im/Export messes up the destination path when 2 mods have the same foders.

### ISSUE THREAD

**Issue by MacTee** [MacTee/KSP-Mod-Admin-aOS#42]
Expected behavior: KSP MA should ex/import the install state of a mod.

Current behavior:
Looks like, when several mods share the same folder and it marked as conflict, it causes wrong behavior.

For example, I have Universal Storage mod and Universal Storage [TAC Pack]. They both share the same folder Universal Storage and also have in archive additional folders with alternative configurations and other additional stuff. After export and import the main folder Universal Storage in both mods lost its installation path. So both mods just don't install.

**Comment by EoD** [comment]
The same happens with the "Astronomers Visual" pack. Even though the folder "GameData/Chatterer" is not shared and it is claimed to be installed, KSPMA does not install the folder.

**Comment by MacTee** [comment]
In progress ...
Problem is the ModSelectionTreeModel::SearchNodeByPath algorythem ...

**Comment by MacTee** [comment]
Fixed with commit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/a138676b673506ea04777a4dbbed7849baf31986
