### ISSUE TITLE
No way of re-downloading mod

### ISSUE THREAD

**Issue by EoD** [MacTee/KSP-Mod-Admin-aOS#44]
I changed the mods folder for KSPMA and moved the mods manually into the new folder. This made all entries in KSPMA turn red and every time I try installing it, it complains about missing zip files even though they are inside the new location.

Apart from that, I wasn't able to re-download the mods in any way. They are still registered with their online location, but when I press "update mod" it says "mod is up to date". Shouldn't it download re-download the mod in such a case?

**Comment by MacTee** [comment]
Good point i find a way to fix it.

**Comment by Gribbleshnibit8** [comment]
I think this would also be a case where dropping the same zip file as an already known mod would simply update the path to the new file. So if moving the mod folder, someone could just drop them all into the program from the new location and it would update without the need to download again.

**Comment by MacTee** [comment]
Fixed with commit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/541ee618d84ed5beee555896480330906a069c67
  
KSP MA will try to redownload a mod, on UpdateMod, if its zip archive is missing.
