### ISSUE TITLE
Add a link to the mod's homepage

### ISSUE THREAD

**Issue by EoD** [MacTee/KSP-Mod-Admin-aOS#48]
It would be really good to be able to click a link to the mod's homepage. You could do this either via the right-click menu in the left "Mods" pane or just provide a link on the right "Mod Infos" pane. The link should already be inside the ModInfo anyway.

**Comment by Gribbleshnibit8** [comment]
I actually enabled this feature in [bfed688](https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/bfed688ad755323c88a7b619fb5495d8355553ac). Enables a button on the Mod Infos side that will take you to the version control page. The drop down provides a button for the alternate link if one is provided.

**Comment by MacTee** [comment]
Implemented with commit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/bfed688ad755323c88a7b619fb5495d8355553ac.
Will be in the next version.
