### ISSUE TITLE
Export mod list as text file

### ISSUE THREAD

**Issue by Gribbleshnibit8** [MacTee/KSP-Mod-Admin-aOS#49]
Add a second option under the Ex/Import button for generating a plain text file of mod names and links to the associated VC sites if available. Allows for sharing of mod list without the other party needing Mod Admin.

**Comment by MacTee** [comment]
Sounds reasonable =)

**Comment by Gribbleshnibit8** [comment]
I've made an initial version of this that performs some simple formatting of the string as checked state, name, and primary URL. It's a sub-button under the Im/Export modpack button. I don't know if you wanted to maybe make a small window for this to allow selection of fields to be output to the file, but I was just thinking a quick export option.

The format is like:

    Name                                                            Url
[x] MechJeb                                                      url.to.mechjeb

**Comment by Gribbleshnibit8** [comment]
Initial preview with just basic export is [here](https://github.com/Gribbleshnibit8/KSP-Mod-Admin-aOS/tree/ModList)

**Comment by MacTee** [comment]
Looks good!
Please just add a new button "ModPack Import/Export" above the "Export to .txt", which opens the ModPack dialog (bind the button to tsbExImport_Click).
I'll add localization and icons when we have merged the changes to the dev branch.

**Comment by MacTee** [comment]
Implemented with commits https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/33fbfe45dc81029f07fdb3baa99949d568c940ae and https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/3d7a710746f6f6cc73fa55f3cd470425e949198a
