### ISSUE TITLE
Mod is marked as outdated when there is no download link

### ISSUE THREAD

**Issue by EoD** [MacTee/KSP-Mod-Admin-aOS#52]
Linux v2.0.0.11

For some reason, I have [Planetshine](http://forum.kerbalspaceprogram.com/threads/96497-0-25-0-90-PlanetShine-v0-2-2-1) (and  [Contracts Window+](https://github.com/DMagic1/KSP_Contract_Window)) in my list with a Github primary URL (i.e. https://github.com/valerian/ksp-planetshine).
KSPMA must have added that link automatically when I added the zip file archive of Planetshine. (This might already be a bug in itself.)

The bug I want to report is the following:
When I click "Check for updates" the program says:
```
[6] Info    : Update check for mod "PlanetShine" via "GitHub" started...
[6] Info    : The mod "PlanetShine" is outdated.
```

and when I click "Update mod":
```
[11] Info    : Update check for mod "PlanetShine" via "GitHub" started...
[11] Info    : The mod "PlanetShine" is outdated.
[11] Info    : Downloading mod update "PlanetShine"...
[11] Debug   : No download link found!
```

**Comment by MacTee** [comment]
KSP MA reads AVC Version files and gets some infos from it, i guess Planetshine has a .version file in its archive somewhere. 
Sould there a popup to inform the user about that? 
(There are messages in the msg window about it)  
   
The message "No download link found!" is missleading and means that there was "No binary download found at the linked version control site". 
I'll replace the old message with "No binary download found at \"{0}\"!".
