### ISSUE TITLE
Copy ModInfos across add-ons versions copies all, but shouldn't

### ISSUE THREAD

**Issue by diomedea** [MacTee/KSP-Mod-Admin-aOS#58]
When a new version of an add-on is released, its zipfile archive is downloaded and added to KSP MA. Unless some form of version control exists (file or site), all ModInfos have to be manually associated with the new version: this is where the Copy ModInfo functionality comes to help, it should allow to copy info fields that were already edited in the previous version of the add-on, to the newer version.

As of KSP MA 2.0.0.11, Copy ModInfo works "too much", actually copying every single field with the newly added add-on version. The fields below shouldn't be copied however:
- Archive Path: this is the greatest mistake, as KSPMA then associates the newer version to the older zipfile. With the effect that the add-on would look at that zipfile instead (if the zipfile is removed being old, the add-on in KSPMA would be considered to have lost the archive, even if the proper zipfile is still existing). The issue here is worsened by the fact that users can't edit that field to correct it.
- Version: as each version number is different, the content of that field can't be copied across versions.

**Comment by MacTee** [comment]
Fixed with commit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/4cc7956e25eae5d860b8fa49b99f02ec003dde4f
