### ISSUE TITLE
KSPMA under Ubuntu wrongly detects screen size with workspaces

### ISSUE THREAD

**Issue by FChapeau** [MacTee/KSP-Mod-Admin-aOS#59]
So, trying to use the software, I ran it in mono. No problem there. I did hit a problem when running KSP since the screen resolution was all messed up. I checked and I saw that the resolution it used was 5760*3240.

I'm using Ubuntu 14.10 and I setup my workspaces in a 3X3 grid. From what I understand, KSPMA detects the workspaces as extra screens and sets the resolution for KSP based on that, which is wrong. Furthermore, the resolution list only contains said resolution, nothing else. Deactivating the workspace feature in Ubuntu's settings fixed the problem, but I like my workspaces.

**Comment by MacTee** [comment]
Should be Fixed with commit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/548adc66d017a05bc36ecb7cd61dd46845cb4b80
