### ISSUE TITLE
Rescan Mod Archives

### ISSUE THREAD

**Issue by Gribbleshnibit8** [MacTee/KSP-Mod-Admin-aOS#60]
When multiple mods include the same file, like modulemanager, they all get tagged as 'installed' and 'conflicted' even when they install the same version.

The ability to remove those from the archive and rescan the archives without needing to remove and re-add the mod would be nice.

**Comment by MacTee** [comment]
I don't want to change the downloaded Mod archive.
To solve your conflict just remove the destination path of the not needed files.

**Comment by Gribbleshnibit8** [comment]
Can there be a key combo or some other faster method of removing destination than opening the dialog for every file then. Probably something set in the settings, user selectable key.
