### ISSUE TITLE
Empty ConflictSolver shows after click on "Process ??? mods" button

### ISSUE THREAD

**Issue by MacTee** [MacTee/KSP-Mod-Admin-aOS#70]
SirSmurfalot:
As with #55 and #42

I am installing all the mods for USI found here:
https://bobpalmer.github.io/UmbraSpaceIndustries/
Two from another developer
ForScience! and Science Exchange
Plus a few stand alone mods.

The USI mods have a lot of overlap shared in configs, DLLs (including a DLL from Firespitter), flags, and other miscellaneous files.

I used the "solve conflicts" option in the context menu to resolve all conflicts by setting them to default to the largest of the mod packs (the MKS/OKS pack) to pull anything with a duplicate conflict from that mod.

Solve conflicts worked just fine with two mods from another developer "For Science" and "Science Exchange".

After solving the conflicts, several of the USI mods were still orange, MKS/OKS, FTT, Karbonite, Explorer pack and Survival Pack-- as well as stand alone version of Firespitter which has a shared DLL used by all itself and all of the affected USI mods. Six mods in total, 5 from USI and Firespitter. Each of the USI mods share the UmbraSpaceIndustries folder, but have different parts contents.

When I went to process modules the solve conflict screen would pop up, but was empty and closing it caused a pop up saying it would not let me continue without solving the conflicts even though no conflicts were listed.

I had to disable the conflict check in the options and manually fix them by unchecking the duplicate files to get them to go from orange to black in order to get them to process and go green.

After processing they all have all the conflicted files that I unchecked are checked again and green as described in here and in #42

If I turn conflict check back on after processing (all green) the same mods become orange again and will no longer process until I turn conflict check back off.

Edit: USI mods that do share the UmbraSpaceIndustries folder, but did not share the Firespitter.dll are unaffected by this conflict problem and loaded normally on the first try.

I hope this helps, let me know if you need other info.

**Comment by MacTee** [comment]
Hi SirSmurfalot,

Thanks for the repoert!

Yes, there was a little bug with the opening of the ConflictSolver.
I have fixed it in commit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/8a0da038019000418afbc23b3427f829219b860c

The checked state and coloring will be discussed in #55

**Comment by SirSmurfalot** [comment]
This is probably a good time to ask how I should update to the new committed versions as you produce them.  It does not appear that the beta version has the auto update enabled to pull new beta versions.  Should I do it manually?

**Comment by MacTee** [comment]
hmm .. auto update is broke again =/
Auto update check is broken too ;(

but the manual update check and download works (on the update tab).
