### ISSUE TITLE
Feature for Conflict Solver 

### ISSUE THREAD

**Issue by SirSmurfalot** [MacTee/KSP-Mod-Admin-aOS#77]
I have several Mods by USI that share 20+ common files packaged with them and they all show as conflicts.  There needs to be an option in Conflict Solver to let the user pick a single parent mod for the group and use it to resolve all conflicts for that group of mods.

Something along the lines of:
"Check here to use module "Foo" to resolve all (n) conflicts with mods 'Snap', 'Crackle' and 'Pop' "

![screenshot 2015-05-08 16 57 43](https://cloud.githubusercontent.com/assets/8341440/7546576/cc0d2f58-f5a4-11e4-9c53-a6801e9abf02.png)

**Comment by MacTee** [comment]
Comes with the 2.0.0.15. Implemented with commit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/eb30c713e358e82b9380e05e4cdb09cc0d7ad536
![image](https://cloud.githubusercontent.com/assets/5434397/7546710/43ee6e88-f5e1-11e4-9c26-5936a0f72064.png)
Maybe i need some help with the TooTip =)

**Comment by SirSmurfalot** [comment]
Wow, very nice.  Practically telepathic.
