### ISSUE TITLE
Backup Plugin

### ISSUE THREAD

**Issue by 4o66** [MacTee/KSP-Mod-Admin-aOS#79]
Enhancement request:

The 1.X Mod Admin had an awesome backup feature, I would love to see that as a plugin.

**Comment by MacTee** [comment]
I'm on it ;)

**Comment by SirSmurfalot** [comment]
That backup function was pretty awesome and useful.

**Comment by MacTee** [comment]
Implemented with merge https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/802537cfc7096d8d28ac19a7b9801babf7b1c588
Just wait for the next release ;)
