### ISSUE TITLE
Downloading from curseforge takes forever

### ISSUE THREAD

**Issue by EoD** [MacTee/KSP-Mod-Admin-aOS#84]
v2.0.0.15 Linux/Windows

When I try downloading [Planetshine http://kerbal.curseforge.com/ksp-mods/224876-planetshine] the "Adding mod" prompt stays up forever even though the download already finished.

**Comment by MacTee** [comment]
Fixed with commit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/5fc20d723c68fcb7f7a74d81283b317e42dbf3a1

**Comment by MacTee** [comment]
This should only happen when the file to download already exists on your HD.

**Comment by EoD** [comment]
Oh yes, I think that was the case in all my tests.
