### ISSUE TITLE
"Remove All" button too easy to press

### ISSUE THREAD

**Issue by blnk2010** [MacTee/KSP-Mod-Admin-aOS#85]
Being so small and right next to the "remove selected" button it's too easy to press accidentally. There isn't a confirm dialog and it automatically deletes all mods.

Suggestion is to add a confirm dialog.

**Comment by MacTee** [comment]
There is a confirm dialog befor KMA² deletes the seleced or all mods.
Did you miss it?

Which version are you useing? Win or Mono?

**Comment by blnk2010** [comment]
I'm using win. The latest version *.15. I don't know how I could have
missed it. I've literally pressed remove all a few times now with no dialog
and all of the mods in my gamedata folder were deleted on accident. It's
really frustrating. I just recently updated from *.14 if that matters.

**Comment by MacTee** [comment]
Every time when i click on of those 
![image](https://cloud.githubusercontent.com/assets/5434397/7553797/a85ba4c4-f70a-11e4-8cba-7ddb918eb747.png) or 
![image](https://cloud.githubusercontent.com/assets/5434397/7553800/bb70bc0c-f70a-11e4-987a-32e8ced9741a.png) i get a confirm dialog 
![image](https://cloud.githubusercontent.com/assets/5434397/7553803/d7917b1a-f70a-11e4-8192-0f2871ed5d9d.png).
Even on a empty ModSelection (in case of remove all).
Is it possible that your enter key is accidently pressed?

**Comment by blnk2010** [comment]
Maybe, it happened more than once, but now it isn't.

**Comment by MacTee** [comment]
Now you get the confirm dialog?

**Comment by MacTee** [comment]
I have added explicit functions for silent removal of mod(s) with commit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/06c3be3e5ae862bfc92f946adf8a344bb8677c32 
Now there is no way that the confirm dialog could be bypassed (no call to the silent mode function in the code, right now).

**Comment by MacTee** [comment]
Has anyone feedback to this "bug"?

**Comment by blnk2010** [comment]
I think this is good now.
