### ISSUE TITLE
Minor Suggestions

### ISSUE THREAD

**Issue by SirSmurfalot** [MacTee/KSP-Mod-Admin-aOS#90]
"Add dialog" should probably read "Add Module"
"Remove all mods" should probably have a confirmation pop-up to prevent accidents.
"Check" and "Uncheck" all mods should probably read "Select" and "Un-select" to differentiate it from the update check feature.
What does "Refresh checked state" even do?

There also used to be a utility for backing up your saved games in the previous versions of MA, are you going to add that back in later?

**Comment by MacTee** [comment]
From now on your name shall be "Add mod" dialog ;)
You can change every single string in <KMA²_installdir>\lang\KSPMA.eng.lang

i'm iritated, cause you are the second user who experienced that the "remove all mods" button doesn't have a confirm dialog. it does, at least on my end. pls see issue https://github.com/MacTee/KSP-Mod-Admin-aOS/issues/85

I have changed it to checked and unchecked cause select could missleading to marked/selected row(s) (after a click or shift/Ctrl+click).

Refresh checked state will run through you mordeslection and looks if a file or folder is installed. if it is it will be checked of not unchecked. the icon of the node will be changed accordingly to its state.
try to change some checkboxes and hit the button ... =)

BackupTab?! see https://github.com/MacTee/KSP-Mod-Admin-aOS/issues/79
