### ISSUE TITLE
Creation of ZIP archives failing

### ISSUE THREAD

**Issue by theslams** [MacTee/KSP-Mod-Admin-aOS#96]
After update to 2.1.0, an error message appears when attempting to create any ZIP archive. "Creating of zip failed. Error message: The path is not of a legal form."

ZIP Archive Path is C:\Users\****\Downloads\KSP Mods

Update: went back to previous dev version (2.0.0.16), same issue. Something about using the autoupdate to get to 2.1.0 did at least two things: (1) many of my mods are now detected as not having zip archives (not true) and (2) I am unable to create the archives to solve the problem.

**Comment by MacTee** [comment]
Sry for your trouble!
I think the problem is that the AutoUpdater can't update the SharpCompress.dll cause it uses it to extract the new KSPMA archive.

Please try to override your current KSP MA installation with all files from
KSPModAdmin-v2.1.0.0_Win.zip\v2.1.0.0\KSP Mod Admin\*.*

**Comment by MacTee** [comment]
Well besides the mentioned problem from above.
The zip creation seems to be broke =/ ...

**Comment by theslams** [comment]
Would it still be helpful for me to test overwriting the install, as you suggest?

**Comment by MacTee** [comment]
I'm not sure, but it can't hurt ;) So please go ahead and replace the files.

**Comment by MacTee** [comment]
FIx with commit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/54694953e9e1050ae7bff5bb9ef7e03d2b3b3eab

**Comment by blnk2010** [comment]
Oh good! When will that be released?
