### ISSUE TITLE
Export ModPack does not work

### ISSUE THREAD

**Issue by 4o66** [MacTee/KSP-Mod-Admin-aOS#97]
Using the export modpack function generates no output file

**Comment by MacTee** [comment]
More details pls.
On my end the export works fine.
Did you updated KMA2 with the auto update?

**Comment by 4o66** [comment]
Of course not, I'm on the most recent Dev build :p 

Stepped through the code but did't see anything that looked like a culprit. 
Only error I see the a "Cannot access a disposed object. Object name: 'frmImExport'."

Only thing in the log is:
[17.05.2015 03:48:26.098] [1] Info    : Exporting to "C:\Users\[name redacted]\Downloads\KSP-MA\ModPack_5_17_2015.modpack".

Same lace of result if I try exporting with/out archives or selecting between some/all mods.
Exporting as .txt works fine.

**Comment by MacTee** [comment]
Fixed with commit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/7eae00ad70af482d4157ba4915cef0c08356e9fc

**Comment by 4o66** [comment]
Confirmed, modpacks now export properly. Thanks!
