### ISSUE TITLE
Flags plugin does not come with a KMA² flag

### ISSUE THREAD

**Issue by 4o66** [MacTee/KSP-Mod-Admin-aOS#99]
I need to be able to fly the KMA² flag in-game.

**Comment by MacTee** [comment]
Thanks that made my day!
Will come soon!

**Comment by MacTee** [comment]
Fixed with commit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/becc1f7dd1593c45b34efa054a52533a0df2784e

**Comment by 4o66** [comment]
Fixed the fix, pull request submitted. (If the MyFlag folder did not exist, flag would not be saved, silent fail.)

**Comment by 4o66** [comment]
Flags in DDS format are not detected.
For an example, use DMagic Orbital Science: http://kerbalstuff.com/mod/5/DMagic_Orbital_Science

**Comment by MacTee** [comment]
Well this sounds so easy, but its not ...
DDS images can't be load with plain c# on the fly.

I have found some promissing code snippets like https://gist.github.com/soeminnminn/e9c4c99867743a717f5b
But here the reading of a dds image don't work. It masses up the header reading (the header.pixelformat.rgbbitcount is 0) which leads to a empty image byte array ...
There is quite some work to do, to support displaying of dd images.

For now i think i'll display only a placeholder image =/ anything else would be to much extra work.

What do you think?

**Comment by MacTee** [comment]
Fixed with commit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/8b92bab68788558fd49d6a21ba210794f216a609

**Comment by 4o66** [comment]
Much better.  Would this help any: https://code.google.com/p/kprojects/downloads/detail?name=DDSImage_0.3.zip&can=2&q=

**Comment by MacTee** [comment]
hmm the one i have found was promissing and your one seems to work better.
But there is still a problem with the DMagic flag. For some reason the header of this flag is different, and both DDSImage classes can't load it properly.
If you want to have a look see commit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/ae9ab437ef8396748709709121edd0859bcda600
To test just add the DMagic_Orbital_Science mod and switch to the falg tab.
Every second click on refresh the DDSImage class will be swapped.

**Comment by MacTee** [comment]
hmm with two extra libs this would work ---> http://freeimage.sourceforge.net/download.html

**Comment by MacTee** [comment]
Moved to #issue 105
